### ISSUE TITLE
Complete Activities Page

### ISSUE THREAD

**Issue by comzeradd** [mozilla/coss#353] opened 2017-09-05 14:35 UTC
- [x] Align with Phase 1 Design
- [x] Change to permanent URL (`/activities/`)

**Comment by comzeradd** [comment] 2017-09-11 07:43
Fixed at 97971976aa85271efcb45a5e15318e3606287f92

**Comment by bacharakis** [comment] 2017-10-18 11:41
Hi there, i am getting a not found page when I try to access opensource.mozilla.community/activities![Screenshot from 2017-10-18 12-40-05.png](https://images.zenhubusercontent.com/57334440bf93871ccd9adcd3/20103bcb-0430-4fd0-8d0f-28991b64b5d3)

**Comment by akatsoulas** [comment] 2017-10-18 12:00
@comzeradd why do we need to change to the url to `activities`?

**Comment by hmitsch** [comment] 2017-10-18 12:58
@bacharakis maybe you can chime in on the question @akatsoulas mentioned above?

**Comment by comzeradd** [comment] 2017-10-18 13:20
The activity page is under `/find-activity/` on the [production site](https://opensource.mozilla.community/find-activity/).

@bacharakis you can easily change that to `/activities/` or anything else you might want by editing the page and editing the `Slug` field on the Promote tab.

**Comment by bacharakis** [comment] 2017-10-18 15:39
Hey all!

I suddenly get an email from Henrik to check these issues. In this issue I see that Nikos has the URL change as a todo.

I don't know from where this decision came from but I am not here to judge that but to test if this is working.

So my comment is to the fact that even though the issue is closed and pushed to production, the URL change is not working.

Given the fact that there is a functionality in place to change the URL and we don't know from where this decision came from, let's leave it that way and close this bug.

**Closed by bacharakis** 2017-10-18 15:39 UTC
Labels: Deliverable, frontend
